name: Deploy Server

on:
  push:
    branches: [master]
    paths:
      - "packages/server/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Echo ref
        run: echo ${{ github.ref }} @ ${{ github.sha }}
      - name: Authenticate on GCloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
      - name: Use gcloud CLI
        run: |
          gcloud auth configure-docker -q
          docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/server
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/server
          gcloud config set run/region us-central1
          gcloud run deploy server --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/server:latest --concurrency=60 --platform managed \
            --port=3000
